#! /usr/bin/env python3
import argparse
import textwrap
from pathlib import Path
from typing import Callable


def create_base_html(app_name: str):
    """ Content function """
    return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{app_name}</title>
        </head>
        <body>
            <div id="content">
                {{%block content %}}{{%endblock %}}
            </div>
        </body>
        </html>
    """


def create_hello_world_html(app_name: str):
    """ Content function """
    return """
        {% extends "base.html" %}

        {% block content %}
            <h1>Hello World!</h1>
        {% endblock %}
    """


def create_views(app_name: str):
    """ Content function """
    return """
        from flask import render_template
        
        
        def hello_world():
            return render_template('hello_world.html')
    """


def create_models(app_name: str):
    """ Content function """
    return """
    if __name__ == "__main__":
        1
    """


def create_forms(app_name: str):
    """ Content function """
    return """
    if __name__ == "__main__":
        1
    """


def create_init(app_name: Path):
    """ Content function """
    return """
        from pathlib import Path
        from flask import Flask
        from .views import hello_world

        def create_app(test_config=None):
            # create and configure the app
            app = Flask(__name__, instance_relative_config=True)
            app.config.from_mapping(
                SECRET_KEY='dev',
                #USERBASE=Path(app.instance_path) / "user",
            )
        
            if test_config is None:
                # load the instance config, if it exists, when not testing
                app.config.from_pyfile(
                    Path(app.instance_path) / 'config.py', 
                    silent=True
                )
            else:
                # load the test config if passed in
                app.config.from_mapping(test_config)
        
            # ensure the instance folder exists
            Path(app.instance_path).mkdir(parents=True, exist_ok=True)
            #Path(app.config["USERBASE"]).mkdir(parents=True, exist_ok=True)
        
            # Routes
            app.add_url_rule('/', 'hello_world', hello_world)
        
            return app
        """


def create_requirements(app_name: Path):
    """ Content function """
    return """
        flask
    """


def create_setup_cfg(app_name: Path):
    """ Content function """
    return f"""
        [metadata]
        name = {app_name}
        version = 0.1.0
        description = Flask-Projekt {app_name}
        long_description = file: README.md
        long_description_content_type = text/markdown
        url = https://github.com/vijfhuizen-c0derz/{app_name}

        [options]
        packages = find:
        install_requires =
            flask

        [options.extras_require]
        test =
            pytest
            coverage
        
        [options.packages.find]
        exclude =
            tests*
        
        [tool:pytest]
        testpaths = tests
        
        [flake8]
        max-line-length = 88
        extend-ignore = E203, W503
    """


def create_app_py(app_name: Path):
    """ Content function """
    return f"""
        #! /usr/bin/env python3
        
        from {app_name} import create_app
        
        app = create_app()
    """


def create_app_wsgi(app_name: Path):
    """ Content function """
    return f"""
        #! /usr/bin/env python3

        import sys
        sys.path.insert(0, "/home/{app_name}/{app_name}")
        from app import app as application
    """


def make_dir(template_path: str):
    """ Return a function that creates a directory `template_path` """

    def create_dir(app_name: str):
        path = template_path.replace("__app__", app_name)
        Path(path).mkdir(parents=True, exist_ok=True)

    return create_dir


def make_file(template_path: str, content_func: Callable):
    """ Return a function that creates a file `template_path`.
        The actual content is provided by the `content_func`
    """

    def create_file(app_name: str):
        path = template_path.replace("__app__", app_name)

        # get the content, dedent it, and delete the leading empty line
        content = content_func(app_name)
        content = textwrap.dedent(content)
        content = content.lstrip()

        # Write it out
        Path(path).write_text(content)

    return create_file


def create_flask_app(app_name: str):
    """ Create the directury structure and file scaffolding for a Flask-application.
    """

    # Filesystem layout: directories and files.
    structure = [
        make_dir("__app__"),
        make_dir("__app__/__app__"),
        make_dir("__app__/__app__/templates"),
        make_dir("__app__/__app__/static"),
        make_dir("__app__/instance"),

        make_file("__app__/__app__/templates/base.html", create_base_html),
        make_file("__app__/__app__/templates/hello_world.html", create_hello_world_html),
        make_file("__app__/__app__/views.py", create_views),
        make_file("__app__/__app__/models.py", create_models),
        make_file("__app__/__app__/forms.py", create_forms),
        make_file("__app__/__app__/__init__.py", create_init),
        make_file("__app__/requirements.txt", create_requirements),
        make_file("__app__/setup.cfg", create_setup_cfg),
        make_file("__app__/app.py", create_app_py),
        make_file("__app__/app.wsgi", create_app_wsgi),
    ]

    # Actualluy creating the structure
    for func in structure:
        func(app_name)


def main():
    parser = argparse.ArgumentParser(description="Erstelle ein Grundgerüst für eine Flask-WSGI-Anwendung.")
    parser.add_argument("app_name", help="Der Name der zu erstellenden Flask-Anwendung")
    args = parser.parse_args()

    create_flask_app(args.app_name)
    print(f"Flask-Anwendung {args.app_name} wurde erstellt.")


if __name__ == "__main__":
    main()
