#! /usr/bin/env python3.11

# TODO
# sudo setup für deploy.
#   Sudoable commands: apache_restart, pip_and_pull, pull_force

import argparse
import json
import os
import pwd
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional, Union

VALID_OPERATIONS = ['create', 'delete', 'show', 'restart', 'update', 'logs']
VALID_PROJECT_TYPES = ['static_site', 'wsgi_site', 'discord_bot']

PROJECT_DIR = Path('/etc/projects')
LOG_DIR = Path('/var/log')

THE_PYTHON = '/usr/bin/python3.11'

args: argparse.Namespace


def debug(*nargs, **kwargs) -> None:
    level = kwargs.pop("level", 1)
    indent = "--" * level
    if args.debug > level:
        print(f"{indent}>>> DEBUG: ", end='')
        print(*nargs, **kwargs)


def delete_file(f: Union[str, Path, os.PathLike, bytes], *, missing_ok=True) -> None:
    """ Unlink a file, with args.debug and args.dry_run support. """
    if not isinstance(f, Path):
        f = Path(f)
    debug(f"unlink(f={f})", level=2)

    if args.dry_run:
        return

    f.unlink(missing_ok=missing_ok)


def chown_tree(start: Union[str, Path, os.PathLike, bytes], username: str, groupname: Optional[str] = None,
               topdown=True):
    """ change the ownership of the file tree starting at `start` to
        the UNIX user `username` and the UNIX group `groupname`.
        When `topdown` is set (the default) change happens from top to bottom,
        otherwise the other way around.
    """
    if not isinstance(start, Path):
        start = Path(start)
    debug(f"chown_tree({start=}, {username=}, {groupname=}, {topdown=})", level=2)
    if args.dry_run:
        return

    if groupname is None:
        groupname = username

    for root, dirs, files in os.walk(start, topdown=topdown):
        for the_dir in dirs:
            dname = Path(root) / the_dir
            shutil.chown(dname, username, groupname)

        for the_file in files:
            fname = Path(root) / the_file
            shutil.chown(fname, username, groupname)

    shutil.chown(start, username, groupname)


def to_file(content: str, filename: Union[str, Path, os.PathLike, bytes], *,
            mode: Optional[int] = None,
            username: Optional[str] = None,
            groupname: Optional[str] = None) -> None:
    if not isinstance(filename, Path):
        filename = Path(filename)
    debug(f"to_file({content=}, {filename=}, {mode=}, {username=}, {groupname=})", level=2)
    if args.dry_run:
        return

    with open(filename, "wt") as f:
        f.write(content)

    if mode is not None:
        os.chmod(filename, mode)

    if username is not None or groupname is not None:
        shutil.chown(filename, username, groupname)


def operation(the_op: str) -> str:
    """ ArgumentParser validator for the positional parameter operation.
        Valid operations are in VALID_OPERATIONS.
        We raise a ValueError for anything else.
    """
    if the_op in VALID_OPERATIONS:
        return the_op

    raise ValueError(f"invalid operation {the_op}, valid operations are {VALID_OPERATIONS}")


def run(cmd: str, *,
        timeout: Optional[int] = None,
        username: Optional[str] = None,
        groupname: Optional[str] = None) -> int:
    """ Run a command, and report
    """
    if timeout is None:
        timeout = 30
    debug(f"run({cmd=}, {timeout=} {username=} {groupname=}", level=2)
    if args.dry_run:
        return 0

    result = subprocess.run(cmd, capture_output=True, shell=True, timeout=timeout, user=username, group=groupname)

    code = result.returncode
    stdout = result.stdout.decode('utf-8')
    stderr = result.stderr.decode('utf-8')

    if code != 0:
        print(f"*** ERROR: exit code={result.returncode}")

    if stdout and args.debug > 1:
        print(f"*** STDOUT: {stdout}")
    if stderr and args.debug > 1:
        print(f"*** STDERR: {stderr}")

    return code


def check_type(the_type: str) -> bool:
    """ ArgumentParser validator for project types. """
    if the_type in VALID_PROJECT_TYPES:
        return True

    return False


def check_project_exists(project: str) -> bool:
    """ predicate is True if a project file exists in PROJECT_DIR """
    p = PROJECT_DIR / project
    return p.exists() and p.is_file()


def check_username_exists(username: str) -> bool:
    """ predicate is True if user exists in system """
    try:
        pwd.getpwnam(username)
        return True
    except KeyError:
        return False


def check_hostname_valid(hostname: str) -> bool:
    """ predicate is True if hostname ends with .snackbag.net """
    if hostname.endswith(".snackbag.net"):
        return True

    return False


def check_github_valid(github: str) -> bool:
    """ predicate is true if github starts with 'git@github.com:' """
    if github.startswith("git@github.com:"):
        return True

    return False


def get_opts():
    """ Parse the program options using ArgumentParser.
        The collected arguments are left in a global variable args.
    """
    global args

    parser = argparse.ArgumentParser()
    parser.add_argument("operation", type=operation, help="one of show, create, delete, restart")
    parser.add_argument("project", help="a valid project name, or 'show projects'")

    parser.add_argument("-d", "--debug",
                        action="count", help="enable debug logging", default=0)
    parser.add_argument("-n", "--dry-run",
                        action="store_true", help="Do not actually perform any actions, just print them.",
                        default=False)

    parser.add_argument("--type", help="one of static_site, wsgi_site or discord_bot")
    parser.add_argument("--hostname", help="hostname ending in .snackbag.net (in create)")
    parser.add_argument("--github", help="git@github.com:...")
    parser.add_argument("--username", help="a unix username to be created (in create)")
    parser.add_argument("--projectdir", help="a subdirectory name in that users home (in create)")
    parser.add_argument("--timeout", type=int, default=30, help="Extend timeout for running commands (defaul: 30s)")

    args = parser.parse_args()
    debug(f"get_opts() -> {args=}")


def load_project_config(project_name: str) -> dict:
    """ Load a project JSON into a dictionary. """
    project_filename = PROJECT_DIR / project_name

    try:
        with open(project_filename, "rt") as project_file:
            config = json.load(project_file)
    except FileNotFoundError:
        raise FileNotFoundError(f"Project file not found: {project_filename}")
    except json.JSONDecodeError as e:
        raise ValueError(f"Error decoding JSON in project file: {e}")

    debug(f"load_project_config({project_name=}) -> {config=}")

    return config


def do_load_project():
    """ Load a project file, except for "show projects", which does not need this. """
    # special case
    if args.operation == "show" and args.project == "projects":
        return

    if not check_project_exists(args.project):
        raise ValueError(f"project {args.project} does not exist")

    project_config = load_project_config(args.project)

    for k, v in project_config.items():
        setattr(args, k, v)


def validate_or_load_opts():
    """ validate the args for args.operation == "create".
        Call do_load_project() for all other operations.
    """
    global args

    if args.operation == "create":
        if not check_type(args.type):
            raise ValueError(f"invalid project type {args.type}, valid types are {VALID_PROJECT_TYPES}")

        if check_project_exists(args.project):
            raise ValueError(f"project {args.project} already exists")

        if not args.username:
            args.username = args.project
        if check_username_exists(args.username):
            raise ValueError(f"username {args.username} already exists")

        if not args.hostname:
            args.hostname = f"{args.project}.snackbag.net"
        if not check_hostname_valid(args.hostname):
            raise ValueError(f"hostname {args.hostname} does not end in '.snackbag.net'")

        if not args.github:
            raise ValueError(f"github is empty; specify --github <somegithub>")
        if not check_github_valid(args.github):
            raise ValueError(f"github {args.github} is not a valid github url 'git@github.com:...")

        if not args.projectdir:
            args.projectdir = args.username
    else:
        do_load_project()

    return


def do_create_user(username: str, project: str, *, mode=0o711) -> str:
    """ Build an useradd command and run it.
        Returns the home of the user we just created.
     """

    debug(f"do_create_user({username=}, {project=}, {mode=}")

    # user must be created
    comment = f"Project {project} owner"
    run(f'/usr/sbin/useradd -m -c "{comment}" {username}')

    if args.dry_run:
        return "/home/dry_run_user"

    u = pwd.getpwnam(username)
    home = u.pw_dir

    # must set a+x so that the content can later be accessed by the webserver
    Path(home).chmod(mode)

    return home


def do_delete_user(username: str) -> int:
    """ Build the userdel command and run it."""
    debug(f"do_delete_user({username=})")

    if args.dry_run:
        return 0

    code = run(f'/usr/sbin/userdel -r {username}')

    return code


def do_create_ssh_key(username: str, home: str) -> str:
    """ Create a new ssh key (id_deploykey) for the user.
        We also create the .ssh directory, as needed, and add a .ssh/config.

        The id_deploykey.pub is returned (the key, not the path to the key).
     """

    debug(f"do_create_ssh_key({username=} {home=})")

    # Step 1: Create $HOME/.ssh
    sshdir = Path(home) / ".ssh"
    if not args.dry_run:
        sshdir.mkdir(0o700, parents=True, exist_ok=True)

    # Step 2: Create $HOME/.ssh/config
    deploykey = f"{sshdir}/id_deploykey"

    to_file(f"""
Host github.com
    HostName github.com
    User git
    IdentityFile {deploykey}
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
""", sshdir / "config", mode=0o644, username=username, groupname=username)

    # Step 3: Create $HOME/.ssh/id_deploykey and save the pubkey
    run(f'ssh-keygen -t rsa -b 4096 -N "" -f {deploykey}')

    if args.dry_run:
        pubkey = "ssh-fake AAAARRGH!== fake@fakebox"
    else:
        pubkey = Path(f"{deploykey}.pub").read_text().strip()

    # Step 4: Chown all the files to the user.
    chown_tree(home, username=username)

    return pubkey


def do_create_projectfile(config):
    """ Create a project file in PROJECT_DIR. """
    debug(f"do_create_projectfile({config=})")

    project_filename = PROJECT_DIR / config.project
    project_desc = {
        "type": config.type,
        "project": config.project,
        "hostname": config.hostname,
        "github": config.github,
        "pubkey": config.pubkey,
        "projectdir": config.projectdir,
        "username": config.username,
        "home": config.home,
    }
    project_file_content = json.dumps(project_desc, indent=2, sort_keys=True) + "\n"
    to_file(project_file_content, project_filename)


def do_delete_project_file(project: str):
    """ Delete the project file in PROJECT_DIR. """
    debug(f"do_delete_project({project=})")

    delete_file(PROJECT_DIR / project)


def do_git_clone(target: Union[str, Path, os.PathLike, bytes], repo: str, username: str, timeout: int):
    """ Perform a git clone of args.github into $HOME/args.projectdir
        as root, then re-owner things to the username provided.

        This is so that we do not need to rely on the deploykey, which is not configured, yet.
    """
    if not isinstance(target, Path):
        target = Path(target)
    debug(f"do_git_clone({target=} {repo=} {username=} {timeout=})")

    run(f"git clone {repo} {target}", timeout=timeout)
    chown_tree(target, username, username)


def do_python_setup(target: Union[str, Path, os.PathLike, bytes], username: str, timeout: int):
    """ Prepare a git checkout for Python usage. """
    if not isinstance(target, Path):
        target = Path(target)
    debug(f"do_python_setup({target= } {username=} {timeout=})")

    if args.dry_run:
        pass
    else:
        os.chdir(target)  # /home/keks/keks

    # Step 1: create venv
    run(f'{THE_PYTHON} -mvenv venv', username=username, groupname=username)

    # Step 2: pip install -U pip wheel
    run(f'venv/bin/python -mpip install -U pip wheel', timeout=timeout, username=username,
        groupname=username)

    # Step 3: pip install -r requirements.txt
    requirements = Path('./requirements.txt')
    if args.dry_run or (requirements.exists() and requirements.is_file()):
        run(f'venv/bin/python -mpip install -r requirements.txt', timeout=timeout, username=username,
            groupname=username)

    to_file("", Path("./.env"), mode=0x600, username=username, groupname=username)


def do_create_apache_config(config):
    """ Create an apache config in /etc/httpd/conf.sites.d/{config.hostname}.conf. """
    debug(f"do_create_apache_config({config=})")

    config_filename = f"/etc/httpd/conf.sites.d/{config.hostname}.conf"
    if config.type == "static_site":
        config_content = f"""
Use VHost {config.hostname}

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
"""
    elif config.type == "wsgi_site":
        config_content = f"""
#   PyApp $host             $title             $appdir                             $unixuser         $unixgroup
Use PyApp {config.hostname} {config.project}   {config.home}/{config.projectdir}   {config.username} {config.username}

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
"""
    else:
        raise ValueError(f"Unsupported type {config.type}")

    to_file(config_content, config_filename)


def do_delete_apache_config(hostname: str):
    """ Delete the apache config in /etc/httpd/conf.sites.d/{hostname}.conf. """
    debug(f"do_delete_apache_config({hostname=})")

    delete_file(f"/etc/httpd/conf.sites.d/{hostname}.conf")


def do_create_systemd_service(project: str, target: str, username: str):
    """ Create a systemd service in /etc/systemd/system/{project}.service. """
    debug(f"do_create_systemd_service({project=} {target=} {username=})")

    config_filename = Path(f"/etc/systemd/system/{project}.service")
    config_content = f"""
[Unit]
Description={project}
After=syslog.target network.target

[Service]
Type=simple
User={username}
Group={username}
StandardOutput=journal
StandardError=journal
WorkingDirectory={target}
ExecStart={target}/venv/bin/python3 {target}/main.py
Restart=always
EnvironmentFile={target}/.env

[Install]
WantedBy=multi-user.target
"""
    to_file(config_content, config_filename)


def do_delete_systemd_service(project: str):
    debug(f"do_delete_systemd_service({project=}")

    delete_file(f"/etc/systemd/system/{project}.service")
    run(f"systemctl daemon-reload")


def do_create_syslog_config(project: str):
    debug(f"do_create_syslog_config({project=}")

    # Step 1: Make sure a log directory and empty log file exist
    rsyslog_target = Path(f"{LOG_DIR}/services/{project}.log")
    if args.dry_run:
        pass
    else:
        rsyslog_target.parent.mkdir(parents=True, exist_ok=True, mode=0o750)  # directory
        shutil.chown(rsyslog_target.parent, user="root", group="adm")
        rsyslog_target.touch(mode=0o644, exist_ok=True)  # empty log file
        shutil.chown(rsyslog_target, user="root", group="adm")

    # Step 2: Make sure a rsyslog config exists
    rsyslog_filename = Path(f"/etc/rsyslog.d/{project}.conf")
    to_file(f'''
template(name="{project}LogFormat" type="string" string="{rsyslog_target}")

if $!_SYSTEMD_UNIT == "{project}.service" then {{
    action(type="omfile" DynaFile="{project}LogFormat")
    stop
}}
''', rsyslog_filename)
    run(f"systemctl restart rsyslog")

    # Step 3: Check if we also need to create a logrotate config
    logrotate_config = Path("/etc/logrotate.d/services")
    if logrotate_config.exists() and logrotate_config.is_file():
        return  # nothing to do

    to_file(f'''{LOG_DIR}/services/*.log {{
    compress
    missingok
    sharedscripts
    delaycompress
    postrotate
        /usr/bin/systemctl -s HUP kill rsyslog.service >/dev/null 2>&1 || true
    endscript
}}
''', logrotate_config, mode=0o644)


def do_delete_syslog_config(project: str):
    debug(f"do_delete_syslog_config({project=})")

    delete_file(f"/etc/rsyslog.d/{project}.conf")
    run(f"systemctl restart rsyslog")


def do_systemd_activation(project: str):
    debug(f"do_systemd_activation({project=})")

    run(f"systemctl daemon-reload")
    run(f"systemctl enable {project}.service")
    run(f"systemctl start {project}.service")


def do_systemd_deactivation(project: str):
    debug(f"do_systemd_deactivation({project=}")

    run(f"systemctl stop {project}.service")
    run(f"systemctl disable {project}.service")


def do_create_site_symlink(hostname: str,
                           home: Union[str, Path, os.PathLike, bytes],
                           projectdir: Union[str, Path, os.PathLike, bytes]):
    """ Symlink from /var/www/{hostname} to {home}/{projectdir}. """
    if not isinstance(home, Path):
        home = Path(home)
    if not isinstance(projectdir, Path):
        projectdir = Path(projectdir)
    debug(f"do_create_site_symlink({hostname=}, {home=}, {projectdir=}")

    to_path = home / projectdir
    if args.dry_run:
        pass
    else:
        Path(f"/var/www/{hostname}").symlink_to(to_path)


def do_delete_site_symlink(hostname: str):
    """ Delete the symlink in /var/www/{hostname}. """
    debug(f"do_delete_site_symlink({hostname=}")

    delete_file(f"/var/www/{hostname}")


def repo_as_https(github: str, subpath: str):
    """ Turn a git@github.com: url into a https url. """
    debug(f"repo_as_https({github=}, {subpath=})", level=1)

    # git@github.com:vijfhuizen-c0derz/deploy.git
    # https://github.com/vijfhuizen-c0derz/deploy
    if github.startswith("git@github.com:"):
        github = github[len("git@github.com:"):]
    if github.endswith(".git"):
        github = github[:-len(".git")]

    return "https://github.com/" + github + "/" + subpath


def show_deployment_banner(hostname: str, repo: str, pubkey: str):
    debug(f"show_deployment_banner({hostname=}, {repo=}, {pubkey=})")

    print(f"""
We have deployed the site 
{hostname}
from 
{repo}

But for the deploy program to be able to update, you need to add the sites' deploy key to their github.

Go to to the sites repo, 
{repo_as_https(repo, "settings/keys/new")}
and add
{pubkey}
""")


def do_create(config):
    """ Execute the necessary create steps. """
    debug(f"do_create()")

    # In all cases, we create a user, an ssh-key and a projectfile, and check out the git repo.
    config.home = do_create_user(config.username, config.project)
    config.pubkey = do_create_ssh_key(config.username, config.home)
    do_create_projectfile(config)
    do_git_clone(target=Path(config.home) / config.projectdir,
                 repo=config.github, username=config.username, timeout=config.timeout)

    if config.type == "static_site":
        do_create_apache_config(config)
        do_create_site_symlink(config.hostname, config.home, config.projectdir)
        do_httpd_restart()
    elif config.type == "wsgi_site":
        do_python_setup(Path(config.home) / config.projectdir, config.username, config.timeout)
        do_create_apache_config(config)
        do_create_site_symlink(config.hostname, config.home, config.projectdir)
        do_httpd_restart()
    elif config.type == "discord_bot":
        do_python_setup(Path(config.home) / config.projectdir, config.username, config.timeout)
        do_create_systemd_service(config.project, Path(config.home) / config.projectdir, username=config.username)
        do_systemd_activation(config.project)
        do_create_syslog_config(config.project)
    else:
        raise RuntimeError(f"Unknown type {config.type}")

    # in all cases, we communicate success and show the deployment banner.
    print(f"project {config.project} ({config.type}) created")
    show_deployment_banner(config.hostname, config.github, config.pubkey)


def show_undeployment_banner(repo: str):
    debug(f"show_undeployment_banner({repo=}")

    url = repo_as_https(repo, "settings/keys")

    print(f'Do not forget to delete the deploy key at {url}.')


def do_delete(config):
    """ Execute the necessary delete steps. """
    debug(f"do_delete()")

    if config.type == "static_site":
        # Clean up the apache
        do_delete_site_symlink(config.hostname)
        do_delete_apache_config(config.hostname)
    elif config.type == "wsgi_site":
        # Clean up the apache
        do_delete_site_symlink(config.hostname)
        do_delete_apache_config(config.hostname)
    elif config.type == "discord_bot":
        # Clean up the service
        do_systemd_deactivation(config.project)
        do_delete_systemd_service(config.project)
        do_delete_syslog_config(config.project)
    else:
        raise RuntimeError(f"Unknown type {config.type}")

    do_delete_project_file(config.project) # first delete the project file
    do_restart(config)  # the restart, so that we do not collect the old domain
    do_delete_user(config.username)  # then delete the user (only possible when nothing is running any more)
    print(f"project {config.project} ({config.type}) deleted")
    show_undeployment_banner(config.github)


def do_show_all_projects():
    """ Subcommand 'show projects' """
    for p in sorted(list(PROJECT_DIR.glob("*"))):
        print(f"- {p.name}")


def do_show_project(project):
    """ Subcommand 'show <projectname>' """
    project = PROJECT_DIR / project
    if not project.exists():
        raise RuntimeError(f"project {project} does not exist")

    with project.open() as f:
        config = json.load(f)

    max_key_len = max(len(key) for key in config)

    print(f"*** PROJECT {project}")
    for k, v in sorted(config.items()):
        print(f"- {k:<{max_key_len}}: {v}")


def do_show(config):
    """ Subcommand 'show' """
    debug(f"do_show()")

    if config.project == "projects":
        do_show_all_projects()
    else:
        do_show_project(config.project)


def collect_httpd_hostnames(directory: Path):
    """ Collect all hostnames a directory and build a MDomain statement for Apache. """
    hostnames = []
    for filename in Path(directory).glob("*"):
        with open(filename, 'r') as file:
            try:
                data = json.load(file)
                if 'hostname' in data:
                    hostnames.append(data['hostname'])
                else:
                    print(f"Warning: {filename} contains no hostname.", file=sys.stderr)
            except json.JSONDecodeError:
                print(f"Warning: Failed to parse {filename} as JSON.", file=sys.stderr)

    return hostnames


def do_systemd_restart(service: str):
    """ Restart a systemd service """
    debug(f"do_systemd_restart({service=})", level=3)

    servicefile = Path(f"/etc/systemd/system/{service}.service")
    if servicefile.exists() and servicefile.is_file():
        run(f"/usr/bin/systemctl stop {service}.service")
        time.sleep(0.5)
        run(f"/usr/bin/systemctl start {service}.service")
        time.sleep(0.5)
    else:
        debug("Service {service} already deleted (no restart).", level=3)


def do_httpd_restart():
    """ Collect domains, generate a ssldomain.conf amd run restart httpd twice, because of certificate management """
    debug(f"do_httpd_restart()", level=2)

    the_hostname = socket.getfqdn()
    hostnames = [the_hostname]
    hostnames.extend(collect_httpd_hostnames(PROJECT_DIR))
    all_hostnames = " ".join(hostnames)
    to_file(f'''Servername {the_hostname}
MDCertificateAgreement accepted
MDPrivateKeys RSA 4096
MDomain {all_hostnames}
''', Path("/etc/httpd/conf.d/ssldomain.conf"))

    debug(f"hostnames collected: {all_hostnames=}", level=2)

    for _ in [1, 2]:
        do_systemd_restart("httpd")

    run("/usr/bin/systemctl status httpd.service")


def do_restart(config):
    debug(f"do_restart()")

    if config.type in ["static_site", "wsgi_site"]:
        collect_httpd_hostnames(PROJECT_DIR)
        do_httpd_restart()
    elif config.type == "discord_bot":
        do_systemd_restart(config.project)
    else:
        raise ValueError(f"Unknown type {config.type}")


def do_update(config) -> None:
    """ Update the deployment git repository as needed.
        Local changes will be overwritten.
    """
    debug(f"do_update()")

    # Move into the right directory
    target = Path(config.home) / config.projectdir
    os.chdir(target)

    # Do we have a venv?
    venv = Path("./venv")
    requirements = Path("./requirements.txt")

    if venv.exists() and venv.is_dir() and requirements.exists() and requirements.is_file():
        run("venv/bin/python -m pip install -r requirements.txt",
            username=config.username, groupname=config.username, timeout=config.timeout)

    # Do we have a .git?
    git = Path(".git")
    if git.exists() and git.is_dir():
        run("git reset --hard",
            username=config.username, groupname=config.username, timeout=config.timeout)  # local changes will be lost
        run("git pull --rebase",
            username=config.username, groupname=config.username, timeout=config.timeout)

    return


def do_logs(config):
    debug(f"do_logs()")

    if config.type in ["static_site", "wsgi_site"]:
        debug(f"exec tail -F {LOG_DIR}/httpd/{{access,error}}-{config.hostname}.log")
        os.execvp('bash', ['bash', '-c', f'tail -F {LOG_DIR}/httpd/{{access,error}}-{config.hostname}.log'])
    elif config.type == "discord_bot":
        debug(f"exec tail -F {LOG_DIR}/services/{config.project}.log")
        os.execvp('bash', ['bash', '-c', f'tail -F {LOG_DIR}/services/{config.project}.log'])
    else:
        raise ValueError(f"Unknown type {type}")


def main():
    get_opts()
    validate_or_load_opts()

    # operation is one of the things in VALID_OPERATIONS
    if args.operation == "create":
        do_create(args)
    elif args.operation == "delete":
        do_delete(args)
    elif args.operation == "show":
        do_show(args)
    elif args.operation == "restart":
        do_restart(args)
    elif args.operation == "update":
        do_update(args)
    elif args.operation == "logs":
        do_logs(args)
    else:
        raise ValueError(f"This can never happen: {args.operation=}")


if __name__ == "__main__":
    main()
