#! /bin/bash

if [ -d venv ]
then
  source venv/bin/activate
else
  exit 1
fi

if [ -f requirements.txt ]
then
  pip install -r requirements.txt
fi

if [ -d .git ]
then
  git reset --hard
  git pull --rebase
fi
