from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from socket import getfqdn

from .models import (
    DeployProject,
    ProxyProject,
    RedirectSiteProject,
    StaticSiteProject,
    WsgiSiteProject,
)

AUTOGENERATED_HEADER = "# autogenerated by deploy, overwritten on next run.\n"


@dataclass(frozen=True)
class ApacheSiteConfig:
    filename: str
    content: str


def render_site_config(project: DeployProject) -> ApacheSiteConfig:
    return ApacheSiteConfig(
        filename=f"{project.hostname}.conf",
        content=AUTOGENERATED_HEADER + _render_site_body(project),
    )


def _render_site_body(project: DeployProject) -> str:
    if isinstance(project, StaticSiteProject):
        appdir = f"{project.home}/{project.project_dir}" if project.home else project.project_dir
        return (
            f"\nUse StaticVHost {project.hostname} {appdir}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, RedirectSiteProject):
        return (
            f"\nUse RedirectVHost {project.hostname} {project.to_hostname}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, WsgiSiteProject):
        appdir = f"{project.home}/{project.project_dir}" if project.home else project.project_dir
        return (
            "\n#   PyApp $host             $title             $appdir"
            "                             $unixuser         $unixgroup\n"
            f"Use PyApp {project.hostname} {project.name}   {appdir}   "
            f"{project.username} {project.username}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, ProxyProject):
        if project.upstream_host == "127.0.0.1" and project.upstream_scheme == "http":
            return (
                f"\nUse ProxyVHost {project.hostname} {project.upstream_port}\n"
                "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
            )
        return (
            f"\n# custom proxy preview for {project.hostname}\n"
            f"# upstream: {project.upstream_scheme}://{project.upstream_host}:{project.upstream_port}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    raise TypeError(f"unsupported project type: {type(project)!r}")


def render_ssldomain_config(hostnames: list[str], *, fqdn: str | None = None) -> str:
    all_hostnames = " ".join([fqdn or getfqdn(), *hostnames])
    return (
        f"Servername {fqdn or getfqdn()}\n"
        "MDCertificateAgreement accepted\n"
        "MDPrivateKeys RSA 4096\n"
        f"MDomain {all_hostnames}\n"
    )


def collect_hostnames(
    projects: Sequence[DeployProject],
    extra_hostnames: Sequence[str],
    *,
    fqdn: str,
) -> list[str]:
    seen = {fqdn}
    collected: list[str] = []
    for hostname in [*extra_hostnames, *(project.hostname for project in projects)]:
        if hostname not in seen:
            seen.add(hostname)
            collected.append(hostname)
    return collected
