from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from socket import getfqdn

from .models import (
    CustomProject,
    DeployProject,
    GoSiteProject,
    ProxyProject,
    RedirectSiteProject,
    StaticSiteProject,
    WsgiSiteProject,
)

AUTOGENERATED_HEADER = "# autogenerated by deploy, overwritten on next run.\n"


@dataclass(frozen=True)
class ApacheSiteConfig:
    filename: str
    content: str


def render_site_config(
    project: DeployProject,
    *,
    fragment_content: str | None = None,
) -> ApacheSiteConfig:
    content = AUTOGENERATED_HEADER + _render_site_body(
        project,
        fragment_content=fragment_content,
    )
    return ApacheSiteConfig(
        filename=f"{project.hostname}.conf",
        content=content,
    )


def _render_site_body(project: DeployProject, *, fragment_content: str | None = None) -> str:
    if isinstance(project, StaticSiteProject):
        appdir = f"{project.home}/{project.project_dir}" if project.home else project.project_dir
        return (
            f"\nUse StaticVHost {project.hostname} {appdir}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, RedirectSiteProject):
        return (
            f"\nUse RedirectVHost {project.hostname} {project.to_hostname}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, WsgiSiteProject):
        appdir = f"{project.home}/{project.project_dir}" if project.home else project.project_dir
        return (
            "\n#   PyApp $host             $title             $appdir"
            "                             $unixuser         $unixgroup\n"
            f"Use PyApp {project.hostname} {project.name}   {appdir}   "
            f"{project.username} {project.username}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, ProxyProject):
        if project.upstream_host == "127.0.0.1" and project.upstream_scheme == "http":
            return (
                f"\nUse ProxyVHost {project.hostname} {project.upstream_port}\n"
                "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
            )
        return (
            f"\n# custom proxy preview for {project.hostname}\n"
            f"# upstream: {project.upstream_scheme}://{project.upstream_host}:{project.upstream_port}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, GoSiteProject):
        return (
            f"\nUse ProxyVHost {project.hostname} {project.upstream_port}\n"
            "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
        )
    if isinstance(project, CustomProject):
        if fragment_content is None:
            return (
                "\n# missing custom config fragment\n"
                "# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n"
            )
        body = fragment_content.rstrip()
        return f"\n{body}\n"
    raise TypeError(f"unsupported project type: {type(project)!r}")


def render_ssldomain_config(hostnames: list[str], *, fqdn: str | None = None) -> str:
    all_hostnames = " ".join([fqdn or getfqdn(), *hostnames])
    return (
        f"Servername {fqdn or getfqdn()}\n"
        "MDCertificateAgreement accepted\n"
        "MDPrivateKeys RSA 4096\n"
        f"MDomain {all_hostnames}\n"
    )


def site_hostnames_from_dir(path: Path) -> list[str]:
    if not path.exists():
        return []
    return sorted(
        file.name.removesuffix(".conf")
        for file in path.glob("*.conf")
        if file.is_file() and file.name.endswith(".conf")
    )


def site_hostnames_from_dirs(paths: Sequence[Path]) -> list[str]:
    hostnames: set[str] = set()
    for path in paths:
        hostnames.update(site_hostnames_from_dir(path))
    return sorted(hostnames)


def collect_hostnames(
    projects: Sequence[DeployProject],
    extra_hostnames: Sequence[str],
    *,
    fqdn: str,
) -> list[str]:
    seen = {fqdn}
    collected: list[str] = []
    for hostname in [*extra_hostnames, *(project.hostname for project in projects)]:
        if hostname not in seen:
            seen.add(hostname)
            collected.append(hostname)
    return collected


def collect_tls_hostnames(
    projects: Sequence[DeployProject],
    *,
    apache_sites_dirs: Sequence[Path],
    fqdn: str,
) -> tuple[list[str], list[str]]:
    managed_hostnames = sorted(project.hostname for project in projects)
    discovered_hostnames = site_hostnames_from_dirs(apache_sites_dirs)
    manual_hostnames = [
        hostname for hostname in discovered_hostnames if hostname not in set(managed_hostnames)
    ]
    return collect_hostnames(projects, discovered_hostnames, fqdn=fqdn), manual_hostnames
